FROM fedora as builder

RUN dnf -y update && \
	dnf -y install lz4 && \
	dnf clean all

COPY cr /cr
RUN tar -c /cr | lz4 -z -9 - /cr.tar.lz4

FROM crac-lambda-checkpoint

COPY --from=builder /cr.tar.lz4 /

ADD restore.cmd.sh /
ENTRYPOINT [ "/bin/bash", "/restore.cmd.sh" ]

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "example.Handler::handleRequest" ]
